
namespace Qtech.AssetManagement.BusinessEntities
{
    public enum Tables
    {
        amQt_Users = 1,
        amQt_UserAccess = 2,
        amQt_CompanyProfile = 3,
        amQt_AssetAccount = 4,
        amQt_AccumulatedDepreciationAccount = 5,
        amQt_DepreciationExpenseAccount = 6,
        amQt_DepreciationMethod = 7,
        amQt_AveragingMethod = 8,
        amQt_FixedAssetSetting = 9,
        amQt_FixedAssetSettingDate = 10,
        amQt_FunctionalLocation = 11,
        amQt_FixedAsset = 12,
        amQt_ChartOfAccount = 13,
        amQt_Personnel = 14,
        amQt_Product = 15,
        amQt_Supplier = 16,
        amQt_PurchaseRequest = 17,
        amQt_PurchaseRequestDetail = 18,
        amQt_Quotation = 19,
        amQt_QuotationDetail = 20,
        amQt_PurchaseOrder = 19,
        amQt_PurchaseOrderDetail = 20,
        amQt_Receiving = 19,
        amQt_ReceivingDetail = 20,
        amQt_Unit = 21,
        amQt_PaymentMode = 22,
        amQt_PurchaseVoucher = 23,
        amQt_AssetType = 24,
        amQt_DepreciationJournal = 25,
        amQt_DepreciationJournalDetail = 26,
        amQt_MaintenanceRequestType = 27,
        amQt_ServiceLevel = 28,
        amQt_FaultSymptoms = 29,
        amQt_FaultArea = 30,
        amQt_MaintenanceRequest = 31,
        amQt_WorkOrderType = 32,
        amQt_MaintenanceJobType = 33,
        amQt_MaintenanceJobTypeVariant = 34,
        amQt_Trade = 35,
        amQt_WorkOrder = 36,
        amQt_ExpenseCategory = 37,
        amQt_WorkOrderHours = 38,
        amQt_Currency = 39,
        amQt_PaymentTerms = 40,
        amQt_AssetCategory = 41,
        amQt_AssetClass = 42,
        amQt_AccountType = 41,
        amQt_AccountClassification = 42,
        amQt_AccountGroup = 43,
        amQt_CapitalizedCost = 44,
        amQt_FixedAssetCapitalizedCost = 45,
        amQt_Disposal = 46,
        amQt_JournalVoucher = 47,
        amQt_JournalVoucherDetail = 48,
        amQt_Asset = 49,
        amQt_Project = 50,
        amQt_AssetCapitalize = 51
    }
}